services:
  app:
    image: tabletop:dev
    container_name: tabletop
    build:
      target: release
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    command: bun run dev
    ports:
      - 2567:2567
    env_file:
      - .env
