services:
  app:
    image: tabletop:latest
    container_name: tabletop
    build:
      target: release
      context: .
      dockerfile: Dockerfile
    command: bun run start
    ports:
      - 2567:2567
    env_file:
      - .env
    restart: always
